Repository divyansh-2005/GAME_PLAYER, pull requests merged in 2024-10, with the labels that each got.

#7 UI bug fixes
  my-project/src/App.css
  my-project/src/App.jsx
  my-project/src/Components/AddGamePage.module.css
  my-project/src/Components/GameSection.jsx
  my-project/src/Components/Header.jsx
Labels: good first issue, gssoc-ext, level 1, hacktoberfest-accepted

#6 Added about and contact page
  BACKEND/package-lock.json
  BACKEND/package.json
  my-project/index.html
  my-project/package-lock.json
  my-project/package.json
  my-project/src/App.jsx
  my-project/src/Components/AboutPage.jsx
  my-project/src/Components/AboutPage.module.css
  my-project/src/Components/ContactPage.jsx
  my-project/src/Components/ContactPage.module.css
Labels: good first issue, gssoc-ext, level 2, hacktoberfest-accepted

#25 Search Game Title Changes
  my-project/package-lock.json
  my-project/src/Components/style.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#56 Additon of All Contributors | Issue #42
  README.md
Labels: gssoc-ext, level 1, hacktoberfest

#53 Ui fixed
  my-project/package-lock.json
  my-project/src/Games/EmojiIntruder/EmojiIntruder.css
  my-project/src/Games/EmojiIntruder/EmojiIntruder.jsx
Labels: gssoc-ext, level 1

#62 To improve the overall layout of the Rock-Paper-Scissors game
  my-project/src/Games/RockPaper Scissors/Game.css
  my-project/src/Games/RockPaper Scissors/Game.jsx
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#147 Bug fix About and Contact Page
  my-project/src/App.css
  my-project/src/Components/AboutPage.jsx
  my-project/src/Games/PingPongGame/Pong.css
Labels: bug, gssoc-ext, level 2

#162 Added favicon for this website
  my-project/index.html
  my-project/public/favicon.png
Labels: bug, gssoc-ext, level 1

#225 Add Tenzi Dice Game
  my-project/package-lock.json
  my-project/package.json
  my-project/src/App.jsx
  my-project/src/Components/GameSection.jsx
  my-project/src/Games/Dice-Game-Tenzi/src/App.tsx
  my-project/src/Games/Dice-Game-Tenzi/src/DiceGameTenzi.tsx
  my-project/src/Games/Dice-Game-Tenzi/src/components/Background.tsx
  my-project/src/Games/Dice-Game-Tenzi/src/components/Die.tsx
  my-project/src/Games/Dice-Game-Tenzi/src/components/Footer.tsx
  my-project/src/Games/Dice-Game-Tenzi/src/style.css
Labels: gssoc-ext, level 3
